# Generated by Django 5.2.11 on 2026-02-12 19:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matricula', models.CharField(help_text='Ex.: PT-ABC / PR-XYZ', max_length=12)),
                ('modelo', models.CharField(help_text='Ex.: C152 / C172 / PA-28', max_length=60)),
                ('fabricante', models.CharField(blank=True, max_length=60)),
                ('combustivel', models.CharField(choices=[('AVGAS_100LL', 'AvGas 100LL'), ('MOGAS', 'Mogas'), ('JET_A1', 'Jet A-1'), ('OUTRO', 'Outro')], default='AVGAS_100LL', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('aeroclube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeronaves', to='accounts.aeroclube')),
            ],
            options={
                'verbose_name': 'Aeronave',
                'verbose_name_plural': 'Aeronaves',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('matricula', models.CharField(blank=True, help_text='Matrícula interna do aeroclube (se houver).', max_length=40)),
                ('ativo', models.BooleanField(default=True)),
                ('aeroclube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='accounts.aeroclube')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('codigo', models.CharField(blank=True, help_text='Identificador interno/abreviação (opcional).', max_length=40)),
                ('ativo', models.BooleanField(default=True)),
                ('aeroclube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrutores', to='accounts.aeroclube')),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
            },
        ),
        migrations.CreateModel(
            name='ParametroAeroclube',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo_desde', models.DateField()),
                ('fator_co2_kg_por_l', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('aeroclube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='accounts.aeroclube')),
            ],
            options={
                'verbose_name': 'Parâmetro do aeroclube',
                'verbose_name_plural': 'Parâmetros do aeroclube',
            },
        ),
        migrations.CreateModel(
            name='PerfilConsumoAeronave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo_desde', models.DateField()),
                ('lph_padrao', models.DecimalField(decimal_places=2, help_text='Litros por hora (referência).', max_digits=6)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('aeroclube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_consumo', to='accounts.aeroclube')),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_consumo', to='operacional.aeronave')),
            ],
            options={
                'verbose_name': 'Perfil de consumo (aeronave)',
                'verbose_name_plural': 'Perfis de consumo (aeronave)',
            },
        ),
        migrations.CreateModel(
            name='SessaoTreinamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_sessao', models.CharField(choices=[('VOO_REAL', 'Voo real'), ('SIMULADOR', 'Simulador')], max_length=12)),
                ('tipo_aula', models.CharField(choices=[('LOCAL', 'Local'), ('NAVEGACAO', 'Navegação'), ('TGL', 'Tráfego / TGL'), ('OUTRA', 'Outra')], default='OUTRA', max_length=12)),
                ('treino_simulador', models.CharField(blank=True, choices=[('PROCEDIMENTOS', 'Procedimentos'), ('MANOBRAS', 'Manobras'), ('TGL', 'TGL'), ('NAVEGACAO', 'Navegação'), ('INSTRUMENTO', 'Instrumento'), ('OUTRO', 'Outro')], max_length=20)),
                ('data', models.DateField()),
                ('tempo_bloco_min', models.PositiveIntegerField(help_text='Tempo de bloco em minutos (ex.: 65).')),
                ('toques', models.PositiveIntegerField(blank=True, help_text='Toques/pousos (se aplicável).', null=True)),
                ('milhas_nauticas', models.DecimalField(blank=True, decimal_places=2, help_text='NM (se aplicável).', max_digits=8, null=True)),
                ('litros_consumidos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lph_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fator_co2_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qnh_hpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('aeroclube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='accounts.aeroclube')),
                ('aeronave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='operacional.aeronave')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='operacional.aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='operacional.instrutor')),
            ],
            options={
                'verbose_name': 'Sessão de treinamento',
                'verbose_name_plural': 'Sessões de treinamento',
            },
        ),
        migrations.AddIndex(
            model_name='aeronave',
            index=models.Index(fields=['aeroclube', 'modelo', 'ativo'], name='operacional_aeroclu_3bb65c_idx'),
        ),
        migrations.AddIndex(
            model_name='aeronave',
            index=models.Index(fields=['aeroclube', 'matricula'], name='operacional_aeroclu_508ba0_idx'),
        ),
        migrations.AddConstraint(
            model_name='aeronave',
            constraint=models.UniqueConstraint(fields=('aeroclube', 'matricula'), name='uq_aeronave_aeroclube_matricula'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['aeroclube', 'nome'], name='operacional_aeroclu_51ac67_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['aeroclube', 'ativo'], name='operacional_aeroclu_289db6_idx'),
        ),
        migrations.AddIndex(
            model_name='instrutor',
            index=models.Index(fields=['aeroclube', 'nome'], name='operacional_aeroclu_b14323_idx'),
        ),
        migrations.AddIndex(
            model_name='instrutor',
            index=models.Index(fields=['aeroclube', 'ativo'], name='operacional_aeroclu_601da9_idx'),
        ),
        migrations.AddIndex(
            model_name='parametroaeroclube',
            index=models.Index(fields=['aeroclube', 'ativo_desde'], name='operacional_aeroclu_5ff122_idx'),
        ),
        migrations.AddConstraint(
            model_name='parametroaeroclube',
            constraint=models.UniqueConstraint(fields=('aeroclube', 'ativo_desde'), name='uq_parametro_aeroclube_ativo_desde'),
        ),
        migrations.AddIndex(
            model_name='perfilconsumoaeronave',
            index=models.Index(fields=['aeroclube', 'aeronave', 'ativo_desde'], name='operacional_aeroclu_882a4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='perfilconsumoaeronave',
            constraint=models.UniqueConstraint(fields=('aeroclube', 'aeronave', 'ativo_desde'), name='uq_perfil_consumo_vigencia'),
        ),
        migrations.AddIndex(
            model_name='sessaotreinamento',
            index=models.Index(fields=['aeroclube', 'data'], name='operacional_aeroclu_2078b3_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaotreinamento',
            index=models.Index(fields=['aeroclube', 'tipo_sessao', 'data'], name='operacional_aeroclu_db1ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaotreinamento',
            index=models.Index(fields=['aeroclube', 'tipo_aula', 'data'], name='operacional_aeroclu_4980f2_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaotreinamento',
            index=models.Index(fields=['aeroclube', 'aluno', 'data'], name='operacional_aeroclu_ee5af5_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaotreinamento',
            index=models.Index(fields=['aeroclube', 'instrutor', 'data'], name='operacional_aeroclu_431586_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessaotreinamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aeronave__isnull', False), ('tipo_sessao', 'VOO_REAL')), ('tipo_sessao', 'SIMULADOR'), _connector='OR'), name='ck_sessao_voo_real_exige_aeronave'),
        ),
        migrations.AddConstraint(
            model_name='sessaotreinamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aeronave__isnull', True), ('tipo_sessao', 'SIMULADOR')), ('tipo_sessao', 'VOO_REAL'), _connector='OR'), name='ck_sessao_simulador_proibe_aeronave'),
        ),
    ]
