# Generated by Django 5.2.11 on 2026-02-12 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineConsumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_aula', models.CharField(choices=[('LOCAL', 'Local'), ('NAVEGACAO', 'Navegação'), ('TGL', 'Tráfego / TGL'), ('OUTRA', 'Outra')], max_length=12)),
                ('ativo_desde', models.DateField()),
                ('indicador_principal', models.CharField(choices=[('LPH', 'L/h'), ('L_POR_TOQUE', 'L/Toque'), ('L_100NM', 'L/100NM')], max_length=20)),
                ('lph_ref', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('l_por_toque_ref', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('l_100nm_ref', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('aeroclube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='accounts.aeroclube')),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='operacional.aeronave')),
            ],
            options={
                'verbose_name': 'Baseline de consumo',
                'verbose_name_plural': 'Baselines de consumo',
                'indexes': [models.Index(fields=['aeroclube', 'aeronave', 'tipo_aula', 'ativo_desde'], name='operacional_aeroclu_769aeb_idx')],
                'constraints': [models.UniqueConstraint(fields=('aeroclube', 'aeronave', 'tipo_aula', 'ativo_desde'), name='uq_baseline_vigencia')],
            },
        ),
    ]
