# Generated by Django 5.2.11 on 2026-02-21 20:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0002_baselineconsumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSessao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('SEM_BASELINE', 'Sem baseline'), ('ACIMA_BASELINE', 'Acima do baseline'), ('DADO_INCOMPLETO', 'Dado incompleto'), ('CONSUMO_ESTIMADO', 'Consumo estimado')], max_length=20)),
                ('severidade', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Atenção'), ('CRIT', 'Crítico')], default='INFO', max_length=10)),
                ('mensagem', models.CharField(max_length=220)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='operacional.sessaotreinamento')),
            ],
            options={
                'verbose_name': 'Alerta da sessão',
                'verbose_name_plural': 'Alertas das sessões',
                'indexes': [models.Index(fields=['tipo', 'severidade'], name='operacional_tipo_ab99a1_idx')],
            },
        ),
    ]
