# Generated by Django 5.2.11 on 2026-02-21 20:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0003_alertasessao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicaSOP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=120)),
                ('texto', models.TextField()),
                ('tipo_aula', models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('NAVEGACAO', 'Navegação'), ('TGL', 'Tráfego / TGL'), ('OUTRA', 'Outra')], help_text='Opcional. Se vazio, vale para qualquer tipo de aula.', max_length=12)),
                ('tipo_alerta', models.CharField(blank=True, choices=[('SEM_BASELINE', 'Sem baseline'), ('ACIMA_BASELINE', 'Acima do baseline'), ('DADO_INCOMPLETO', 'Dado incompleto'), ('CONSUMO_ESTIMADO', 'Consumo estimado')], help_text='Opcional. Se vazio, vale para qualquer alerta.', max_length=20)),
                ('aeronave_modelo', models.CharField(blank=True, help_text='Opcional. Ex.: C152. Se vazio, vale para qualquer aeronave.', max_length=60)),
                ('prioridade', models.PositiveIntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dica SOP',
                'verbose_name_plural': 'Dicas SOP',
                'indexes': [models.Index(fields=['ativo', 'prioridade'], name='operacional_ativo_f2cdcf_idx'), models.Index(fields=['tipo_aula', 'tipo_alerta'], name='operacional_tipo_au_e87f09_idx')],
            },
        ),
    ]
