# Generated by Django 5.2.11 on 2026-02-12 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroclube',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=180)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aeroclube / Escola',
                'verbose_name_plural': 'Aeroclubes / Escolas',
                'indexes': [models.Index(fields=['nome'], name='accounts_ae_nome_56cfcb_idx')],
            },
        ),
        migrations.CreateModel(
            name='MembroAeroclube',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel', models.CharField(choices=[('ADMIN', 'Admin'), ('GESTOR', 'Gestor'), ('INSTRUTOR', 'Instrutor'), ('ALUNO', 'Aluno'), ('LEITOR', 'Leitor')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('aeroclube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='accounts.aeroclube')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_voa_limpo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro do aeroclube',
                'verbose_name_plural': 'Membros do aeroclube',
                'indexes': [models.Index(fields=['aeroclube', 'papel', 'ativo'], name='accounts_me_aeroclu_34693c_idx')],
                'constraints': [models.UniqueConstraint(fields=('aeroclube', 'user'), name='uq_membro_aeroclube_user')],
            },
        ),
    ]
